{
 "title": "LAN Manager",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Game",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by(game, game_label, game_icon) (lan_game_active > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playtime over Range",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(game, game_label, game_icon) (increase(lan_game_seconds_total[$__range]))",
     "legendFormat": "{{game_label}}"
    }
   ]
  },
  {
   "title": "Players for each game",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lan_game_active > 0", "legendFormat": "__auto" }
   ]
  }
 ]
}