// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::user_info_type::UserInfo;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetUserinfoArgs {
    pub info: UserInfo,
}

impl From<SetUserinfoArgs> for super::Reducer {
    fn from(args: SetUserinfoArgs) -> Self {
        Self::SetUserinfo { info: args.info }
    }
}

impl __sdk::InModule for SetUserinfoArgs {
    type Module = super::RemoteModule;
}

pub struct SetUserinfoCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_userinfo`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_userinfo {
    /// Request that the remote module invoke the reducer `set_userinfo` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_userinfo`] callbacks.
    fn set_userinfo(&self, info: UserInfo) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_userinfo`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetUserinfoCallbackId`] can be passed to [`Self::remove_on_set_userinfo`]
    /// to cancel the callback.
    fn on_set_userinfo(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &UserInfo) + Send + 'static,
    ) -> SetUserinfoCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_userinfo`],
    /// causing it not to run in the future.
    fn remove_on_set_userinfo(&self, callback: SetUserinfoCallbackId);
}

impl set_userinfo for super::RemoteReducers {
    fn set_userinfo(&self, info: UserInfo) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_userinfo", SetUserinfoArgs { info })
    }
    fn on_set_userinfo(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &UserInfo) + Send + 'static,
    ) -> SetUserinfoCallbackId {
        SetUserinfoCallbackId(self.imp.on_reducer(
            "set_userinfo",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetUserinfo { info },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, info)
            }),
        ))
    }
    fn remove_on_set_userinfo(&self, callback: SetUserinfoCallbackId) {
        self.imp.remove_on_reducer("set_userinfo", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_userinfo`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_userinfo {
    /// Set the call-reducer flags for the reducer `set_userinfo` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_userinfo(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_userinfo for super::SetReducerFlags {
    fn set_userinfo(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_userinfo", flags);
    }
}
