// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGamesArgs {
    pub names: Vec<String>,
}

impl From<SetGamesArgs> for super::Reducer {
    fn from(args: SetGamesArgs) -> Self {
        Self::SetGames { names: args.names }
    }
}

impl __sdk::InModule for SetGamesArgs {
    type Module = super::RemoteModule;
}

pub struct SetGamesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_games`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_games {
    /// Request that the remote module invoke the reducer `set_games` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_games`] callbacks.
    fn set_games(&self, names: Vec<String>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_games`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetGamesCallbackId`] can be passed to [`Self::remove_on_set_games`]
    /// to cancel the callback.
    fn on_set_games(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<String>) + Send + 'static,
    ) -> SetGamesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_games`],
    /// causing it not to run in the future.
    fn remove_on_set_games(&self, callback: SetGamesCallbackId);
}

impl set_games for super::RemoteReducers {
    fn set_games(&self, names: Vec<String>) -> __sdk::Result<()> {
        self.imp.call_reducer("set_games", SetGamesArgs { names })
    }
    fn on_set_games(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<String>) + Send + 'static,
    ) -> SetGamesCallbackId {
        SetGamesCallbackId(self.imp.on_reducer(
            "set_games",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetGames { names },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, names)
            }),
        ))
    }
    fn remove_on_set_games(&self, callback: SetGamesCallbackId) {
        self.imp.remove_on_reducer("set_games", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_games`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_games {
    /// Set the call-reducer flags for the reducer `set_games` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_games(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_games for super::SetReducerFlags {
    fn set_games(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_games", flags);
    }
}
